version: "3.9"

services:
  nginx:
    image: hamzat4/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - app-network

  client:
    image: hamzat4/client:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  server:
    image: hamzat4/server:latest
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=your-rds-endpoint.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=filesystem_db
      - MYSQL_USER=fs_user
      - MYSQL_PASSWORD=fs_pass
      - FILESYSTEM_SERVICE_URL=http://filesystem:8081
    depends_on:
      - filesystem
    networks:
      - app-network

  filesystem:
    image: hamzat4/filesystem:latest
    ports:
      - "8081:8081"
    volumes:
      - filesystem_data:/data
    networks:
      - app-network

  executor-java:
    image: hamzat4/executor-java:latest
    ports:
      - "8083:8083"
    networks:
      - app-network

  executor-python:
    image: hamzat4/executor-python:latest
    ports:
      - "8084:8084"
    networks:
      - app-network

  executor-c:
    image: hamzat4/executor-c:latest
    ports:
      - "8085:8085"
    networks:
      - app-network

  executor-cpp:
    image: hamzat4/executor-cpp:latest
    ports:
      - "8086:8086"
    networks:
      - app-network

  executor-js:
    image: hamzat4/executor-js:latest
    ports:
      - "8087:8087"
    networks:
      - app-network

  executor-ruby:
    image: hamzat4/executor-ruby:latest
    ports:
      - "8088:8088"
    networks:
      - app-network

volumes:
  filesystem_data:

networks:
  app-network:
    driver: bridge
