name: Deploy to EC2 via Bastion

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key for Bastion
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/bastion_key.pem
        chmod 600 ~/.ssh/bastion_key.pem
        ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via Bastion to Target EC2
      run: |
        ssh -i ~/.ssh/bastion_key.pem ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} << 'ENDSSH'
          ssh -o StrictHostKeyChecking=no ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_PRIVATE_IP }} << 'INNERSSH'
            docker-compose pull
            docker-compose up -d
          INNERSSH
        ENDSSH
