name: Deploy to EC2 via Bastion

on:
  workflow_run:
    workflows: ["Test Server, Build, and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key for Bastion
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/bastion_key.pem
        chmod 600 ~/.ssh/bastion_key.pem

    - name: Deploy via Bastion to Target EC2 
      run: |
        ssh -i ~/.ssh/bastion_key.pem -o StrictHostKeyChecking=no ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} "
          ssh -i ~/bastion-key.pem -o StrictHostKeyChecking=no ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_PRIVATE_IP }} '
            docker-compose pull &&
            docker-compose up -d
          '
        "
