name: Test Server, Build, and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest
    name: Test Server Service Before Build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17 for Server
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Server Tests (Maven)
      working-directory: ./server
      run: ./mvnw test

  build-and-push:
    needs: test-server  # Wait for server tests to pass before building
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [client, server, filesystem, executor-java, executor-python, executor-c, executor-cpp, executor-js, executor-ruby, nginx]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push ${{ matrix.service }}
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: hamzat4/${{ matrix.service }}:latest
